import json
import xml.etree.ElementTree as ET

from bpmn_assistant.config import logger
from bpmn_assistant.services import BpmnProcessTransformer


class BpmnXmlGenerator:
    """
    Class to generate BPMN XML from the BPMN process data in JSON format.
    """

    def __init__(self):
        self.transformer = BpmnProcessTransformer()

    def create_bpmn_xml(self, process: list[dict], lanes: list[dict] | None = None) -> str:
        """
        Create BPMN XML from the process data.
        Args:
            process: BPMN process structure generated by the LLM.
            lanes: Optional list of lane definitions.
        Returns:
            The BPMN XML string.
        """

        transformed_process = self.transformer.transform(process)
        logger.debug(
            f"Transformed process:\n{json.dumps(transformed_process, indent=2)}"
        )

        # Create the root element (definitions)
        root = ET.Element("definitions")
        root.set("xmlns", "http://www.omg.org/spec/BPMN/20100524/MODEL")
        root.set("xmlns:bpmndi", "http://www.omg.org/spec/BPMN/20100524/DI")
        root.set("xmlns:dc", "http://www.omg.org/spec/DD/20100524/DC")
        root.set("xmlns:di", "http://www.omg.org/spec/DD/20100524/DI")
        root.set("id", "definitions_1")

        # Create the process element
        process_element = ET.SubElement(root, "process")
        process_element.set("id", "Process_1")
        process_element.set("isExecutable", "false")

        # Add laneSet if lanes are provided
        if lanes:
            # Build a mapping of element_id -> lane_id from transformed elements
            element_lane_map: dict[str, str] = {}
            for element in transformed_process["elements"]:
                lane_id = element.get("lane")
                if lane_id:
                    element_lane_map[element["id"]] = lane_id

            lane_set = ET.SubElement(process_element, "laneSet")
            lane_set.set("id", "LaneSet_1")
            for lane_def in lanes:
                lane_elem = ET.SubElement(lane_set, "lane")
                lane_elem.set("id", lane_def["id"])
                lane_elem.set("name", lane_def["name"])
                # Add flowNodeRef for each element belonging to this lane
                for elem_id, elem_lane_id in element_lane_map.items():
                    if elem_lane_id == lane_def["id"]:
                        flow_node_ref = ET.SubElement(lane_elem, "flowNodeRef")
                        flow_node_ref.text = elem_id

        # Add elements
        for element in transformed_process["elements"]:
            elem = ET.SubElement(process_element, element["type"])
            elem.set("id", element["id"])

            # Add label if it exists
            if element["label"]:
                elem.set("name", element["label"])

            # Add default flow attribute for inclusive/exclusive gateways if it exists
            if "default_flow" in element and element["default_flow"]:
                elem.set("default", element["default_flow"])

            # Add incoming and outgoing flows as child elements
            for incoming in element["incoming"]:
                ET.SubElement(elem, "incoming").text = incoming
            for outgoing in element["outgoing"]:
                ET.SubElement(elem, "outgoing").text = outgoing

            # Add event definition if it exists
            if "eventDefinition" in element and element["eventDefinition"]:
                event_def_type = element["eventDefinition"]
                # Create event definition element with a unique ID
                event_def_elem = ET.SubElement(elem, event_def_type)
                event_def_elem.set("id", f"{event_def_type}_{element['id']}")

        # Add flows
        for flow in transformed_process["flows"]:
            seq_flow = ET.SubElement(process_element, "sequenceFlow")
            seq_flow.set("id", flow["id"])
            seq_flow.set("sourceRef", flow["sourceRef"])
            seq_flow.set("targetRef", flow["targetRef"])

            # Add condition if it exists
            if flow["condition"]:
                seq_flow.set("name", flow["condition"])

        xml_string = ET.tostring(root, encoding="unicode")

        return xml_string
